import { ref, onValue, get, push, set, serverTimestamp } from 'firebase/database';
import { database, initError } from './config';

/**
 * Service for Attendance Firebase Realtime Database operations.
 * Works seamlessly with existing ESP8266 schema under `/attendance`.
 */

const ATTENDANCE_PATH = 'attendance';

/**
 * Subscribes to real-time updates from `/attendance`
 * @param {function} onData - Callback with formatted array of records (newest first)
 * @param {function} onError - Error callback
 * @returns {function} Unsubscribe function
 */
export function subscribeToAttendance(onData, onError) {
  if (!database) {
    if (onError) onError(initError || new Error("Firebase database not initialized"));
    return () => {};
  }

  const attendanceRef = ref(database, ATTENDANCE_PATH);

  const unsubscribe = onValue(
    attendanceRef,
    (snapshot) => {
      const val = snapshot.val();
      if (!val) {
        onData([]);
        return;
      }

      // Convert Firebase object/dictionary to sorted array (newest first)
      const records = [];
      Object.keys(val).forEach((key) => {
        const item = val[key];
        if (item && typeof item === 'object') {
          records.push({
            id: key,
            ...item
          });
        }
      });

      // Reverse so newest entries appear at the top
      // (Firebase keys generated by push() or chronological order)
      records.reverse();

      onData(records);
    },
    (error) => {
      console.error("Firebase attendance subscription error:", error);
      if (onError) onError(error);
    }
  );

  return unsubscribe;
}

/**
 * Single-shot fetch of attendance records
 */
export async function getAttendance() {
  if (!database) throw initError || new Error("Firebase database not initialized");

  const attendanceRef = ref(database, ATTENDANCE_PATH);
  const snapshot = await get(attendanceRef);
  const val = snapshot.val();

  if (!val) return [];

  const records = [];
  Object.keys(val).forEach((key) => {
    const item = val[key];
    if (item && typeof item === 'object') {
      records.push({
        id: key,
        ...item
      });
    }
  });

  return records.reverse();
}

/**
 * Add a test attendance scan record (Simulates an ESP8266 RFID scan)
 * Adds the exact structure ESP8266 sends: uid, name, roll, status, device
 */
export async function addAttendanceRecord(record) {
  if (!database) throw initError || new Error("Firebase database not initialized");

  const attendanceRef = ref(database, ATTENDANCE_PATH);
  const newRecordRef = push(attendanceRef);

  const payload = {
    uid: record.uid || 'UNKNOWN',
    name: record.name || 'Unknown Student',
    roll: record.roll || 'N/A',
    status: record.status || 'Present',
    device: record.device || 'SmartAttend',
    timestamp: Date.now() // Adds client/server timestamp for new records while legacy ones remain untouched
  };

  await set(newRecordRef, payload);
  return { id: newRecordRef.key, ...payload };
}

/**
 * Subscribes to Firebase connection state (/.info/connected)
 */
export function subscribeToFirebaseConnection(onStatusChange) {
  if (!database) {
    onStatusChange(false);
    return () => {};
  }

  const connectedRef = ref(database, '.info/connected');
  return onValue(connectedRef, (snap) => {
    onStatusChange(Boolean(snap.val()));
  });
}
